# Generated by Django 4.2.5 on 2023-10-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='kid1',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='kid2',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='kid3',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='kid4',
            field=models.CharField(default=''),
        ),
    ]
