# Generated by Django 4.2.5 on 2023-10-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_account_kid1_alter_account_kid2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Position',
            field=models.IntegerField(default=0),
        ),
    ]
