# Generated by Django 4.2.5 on 2023-10-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_account_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Position',
            new_name='position',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('destination', models.CharField(max_length=50)),
                ('meeting', models.DateTimeField()),
                ('ending', models.DateTimeField()),
                ('departure', models.CharField(max_length=100)),
                ('arrival', models.CharField(max_length=100)),
                ('people', models.ManyToManyField(blank=True, related_name='accounts', to='core.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='accounts', to='core.event'),
        ),
    ]
