# Generated by Django 4.2.5 on 2023-10-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_position_account_position_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='addres',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='account',
            name='mobile',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AddField(
            model_name='account',
            name='psc',
            field=models.CharField(default=''),
        ),
    ]
