# Generated by Django 4.2.7 on 2024-01-03 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_remove_account_users_alter_member_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2024, 1, 3, 0, 54, 12, 312239, tzinfo=datetime.timezone.utc)),
        ),
    ]
