# Generated by Django 4.2.7 on 2024-01-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_event_capacity_event_description_event_travel'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizedBy',
            field=models.CharField(default='turistaklitomici@gmail.cz'),
        ),
    ]
