# Generated by Django 4.2.7 on 2024-02-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_event_organizedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='arrival',
            field=models.CharField(blank=True, default='Včas upřesníme', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='destination',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.CharField(blank=True, default='Dobrou náladu', max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizedBy',
            field=models.CharField(default='turistaklitomici@gmail.cz', max_length=100),
        ),
    ]
