# Generated by Django 4.2.7 on 2024-01-08 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_member_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2024, 1, 8, 22, 24, 42, 65886, tzinfo=datetime.timezone.utc)),
        ),
    ]
