# Generated by Django 4.2.7 on 2024-02-18 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_alter_member_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2024, 2, 18, 21, 38, 31, 45310, tzinfo=datetime.timezone.utc)),
        ),
    ]
