# Generated by Django 4.2.7 on 2024-02-29 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_alter_member_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='addres1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='addres2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='city1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='city2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='psc1',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='account',
            name='psc2',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2024, 2, 29, 21, 22, 53, 609573, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='healthProblems',
            field=models.CharField(default='Dítě nemá žádná zdravotní omezení ani speciální požadavky na stravu či zacházení', max_length=500),
        ),
    ]
